title: jekyll-glass
author:
  name: Linus Warnatz
  email: linus@libewa.xyz
description: >- # this means to ignore newlines until "baseurl:"
  A simple Jekyll theme for blogging, using glass blocks as a design element.
baseurl: "/jekyll-glass" # the subpath of your site, e.g. /blog
url: "libewa.xyz" # the base hostname & protocol for your site, e.g. http://example.com

tag_page_layout: tag
tag_page_dir: tag

social_links:
  - { title: "GitHub", user_url: "https://github.com/libewa/jekyll-glass" }

static_links:
  - { title: "Home", url: "/index" }
  - { title: "Contact", url: "/contact" }
  - { title: "Posts", url: "/posts" }
  - { title: "Feed", url: "/feed.xml" }

show_excerpts: true

# Build settings
plugins:
- jekyll-feed
- jekyll/tagging
- jekyll-sitemap
- jekyll-font-awesome-sass

font-awesome:
  assets: true